<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Safe Online Banking</title>
        
        <link rel="stylesheet" href="newcss.css">
        <style>
            .heading{
    font-weight:bold;
    color:#2E4372;
}
        </style>
       
    </head>
        <?php include 'header.php' ?>
        <div class='content_customer'>
            <h3 style="text-align:center;color:#2E4372;"><u>Terms and conditions</u></h3>
              
            <div class="contact" style="overflow: scroll;">
             
            The following Terms and Conditions govern your use of Personal Internet Banking offered by Bank INDIA, N.A. () for accounts held at Bank INDIA, N.A. or any of its subsidiaries or affiliates that hold a Linked Account or provide Personal Internet Banking Services. By using Personal Internet Banking, you agree to these Terms and Conditions. You may print this document for your files or you can request a copy by mail by calling Customer Service at 1-800-975-bank (1-800-975-4722). Representatives are available Monday - Sunday 7:00am - 12:00am ET. Or you can write to: bank Bank INDIA, National Association, P.O. Box 2013, Buffalo, NY 14240.
Types of Available Transfers and Services<br/>
Here's what you'll be able to do on your computer with Personal Internet Banking:<br/>
Obtain available balance information for Deposit, Credit Card and Line of Credit Accounts as of the close of business on the preceding Business Day. However, debits initiated for Bill Payments, may not be reflected in the Available Balance until the next business day or later, and credits initiated for credit cards, loans and lines are not reflected in the Available Balance until after two business days. Obtain transaction/balance information as provided by Pershing for investments (Brokerage) accounts using the link to the Pershing website.
Review transaction information for the last twenty-four months or two years of statement periods for deposit accounts (ie. a savings account with a quarterly statement would display eight statement dates). Review transaction information for the last twelve statement periods for revolving credit accounts, and the last twenty-four months, or fifty transactions for mortgage accounts.
Make transfers from your checking, savings or other asset accounts or revolving credit accounts to your checking, savings or other asset accounts, bank revolving credit, installment loan or mortgage accounts.
Access information on bank products and services.<br/>
Obtain a summary of checking, savings, money market, CDs, IRAs, or other asset accounts, revolving credit cards, installment loans and mortgage accounts.
Send BankMail (secured email) to us.<br/>
Register for the Bill Pay service to pay bills or make payments from your account to a business or person in the United States.<br/>
Register for the Bank to Bank Transfers service to transfer funds to or from your bank accounts and any other account held by you at another U.S. financial institution.
View, print and download electronic statements or notices and disclosures by enrolling in the eStatement Service, which will also cancel your paper statement. bank online-only accounts receive only electronic delivery of statements, notices and disclosures.
Access your bank Securities (INDIA) Inc. brokerage account (See the End User Agreement for terms and conditions applying specifically to access to your brokerage account online). Securities and Annuity Products are: Not a deposit or other obligation of the bank or any of its affiliates; Not FDIC insured or insured by any federal government agency of the United States; Not guaranteed by the bank or any of its affiliates; and are subject to investment risk, including possible loss of principal invested.
Certain types of transactions within Personal Internet Banking may require additional authentication using an bank Security Device.<br/>
Account Access
Access information about the following types of Accounts:
bank Bank Products
Checking Accounts
Savings Accounts
Certificate of Deposit Accounts (CDs)
Individual Retirement Accounts (IRAs)
Investment Accounts
Line of Credit Accounts
Installment Loans
Mortgages
Credit Cards
Charge Cards
Home Equity
bank online-only Products
Online Savings Accounts
Online Payment Accounts
Online Certificate Accounts
bank Securities (INDIA) Inc. Accounts
Accounts Not Eligible for Access
Fiduciary accounts<br/>
Any account that requires two or more signatures.
Any account in the name of a child under 18 years of age.
Any person you have authorized to access your Personal Internet Banking Account is authorized to:
Accept these Terms and Conditions, as amended from time to time
Access each eligible Account of yours in any manner and for any purpose available through Personal Internet Banking, whether available now or available at some time in the future. Access includes making transactions on linked accounts, such as checking or brokerage accounts.
You agree that any eligible Account opened at a future date will automatically be linked to Personal Internet Banking.
Removal of Account Access<br/>
You may remove access to any Account by notifying bank by BankMail or by other written correspondence. All bank online-only accounts require that you access the accounts only through Personal Internet Banking and such accounts will need to be closed if you want to remove online access.
Your Log On Credentials<br/>
Your log on credentials are used to identify you when accessing Personal Internet Banking. They act as your signature. For information regarding creating a strong password, please click here.
You can change your log on credentials at any time. For your protection, you should memorize your log on credentials and not keep any notation of them on or with your computer. Your log on credentials assure that only you, or someone to whom you give your log on credentials, can access your Internet Banking Account. You agree not to give your log on credentials to anyone you do not authorize to use your Internet Banking Account. If you do, you will be responsible for any money withdrawn or transferred from your Accounts when such person uses your log on credentials.
If any of your Accounts are joint accounts or have additional authorized signers, each owner, or authorized signer is entitled to and should have their own log on credentials to access their Personal Internet Banking Account. The sharing of credentials is not recommended and could potentially place your information at risk. To register joint holders and authorized signers should call the Customer Relationship Center at 1-800-975-4722 or sign up for Personal Internet Banking by visiting us.hsbc.com and selecting "Register" in the top right hand corner to create individual log on credentials.
You understand and agree that to the extent permitted under applicable law each owner of an Account is jointly and individually responsible for all Personal Internet Banking transactions that affect that Account, including the initiation of brokerage account transactions using Personal Internet Banking.
Limitations on Frequency of Transfers and Dollar Amounts
You may use Personal Internet Banking and the Bill Pay service as often as you would like. Internet transfers or Bill Payments must not exceed your Available Balance in the Account on the day the transfer is made, unless you have authorized bank to use your usable balance from your bank Premier with Sweep Account, or your Asset Management Account, or your Commercial Asset Management Account, or your Money Market Fund Account, or your Money Market Mutual Fund Account, or available credit from your MasterCard®, VISA®, Select Credit Account or Express Line Account. Transfers from your line of credit account are subject to the terms of the credit agreement. Transactions on your linked brokerage account are subject to limitation under these Terms and Conditions and the terms of your customer agreement with bank Securities (INDIA) Inc. and the End User Agreement between you and bank Securities (INDIA) Inc. and Pershing LLC. If you make Personal Internet Banking Transfers from your savings account to another of your Accounts, those transfers are counted as telephone transfers and are subject to the Transfer Limits contained in the Rules for Deposit Accounts. If you exceed the transfer limits, then bank may be required to close your savings account and transfer the balance to a checking account.
Transfer Processing<br/>
Date of Immediate Transfer Request	Date Immediate Transfer will be made
On a Business Day - before
Approximately 8 p.m. Eastern Time	Same Business Day that the transfer is requested.1
On a Business Day - after
Approximately 8 p.m. Eastern Time	Transaction will post the next Business Day after the transfer is requested.1
On a day other than a Business Day	Transaction will post the next Business Day after the transfer is requested.1
Date of Scheduled Transfer Request	Date Scheduled Transfer will be made
On a Business Day2	Transaction will post the same Business Day at approximately 7 p.m. ET on the day the transfer was scheduled.3
On a day other than a Business Day	Transaction will post the next Business Day at approximately 7 p.m. ET after the day the transfer was scheduled.3
1 If transferring to an bank Bank INDIA, N.A. deposit account, the funds are available upon completion of the transfer.
2 When scheduling recurring transfers, if the first transfer is scheduled for the same Business Day the request is made, the first transaction will follow the "Date of Immediate Transfer Request" rules and the remaining scheduled transfers will follow the "Date of Scheduled Transfer Request" rules.
3 If transferring to an bank Bank INDIA, N.A. deposit account, the funds are available after 7 p.m. E T on the date the transfer was made.
You may cancel or make changes to a future transfer up to approximately 7 p.m. ET on the day of the Scheduled Transfer by finding the transfer in 'Scheduled Transfers'. Select an account or a date range to narrow your search. Select the transfer by clicking on the date, and then you can modify or delete the transfer.
bank may reject a transfer instruction if there are insufficient Available Funds in your Account, or in the usable balance in your bank Premier with Sweep Account, Asset Management Account, Commercial Asset Management Account, or Money Market Mutual Fund Account, or available credit on your related line of credit, or for any other reason. In the event of insufficient Available Funds on a future transfer, a BankMail notification will be sent to you.
Wire Transfers<br/>
Wire Transfers are governed by the Funds Transfer provisions of the Rules for Deposit Accounts.
Bill Payment Processing<br/>
The Bill Pay service allows you to use your accounts to pay a bill or to make payments to a business or other payee that has a mailing address within the U.S. You agree not to use the Bill Pay service to make any tax payments or any court-ordered payments. You agree that if you attempt to make payments for taxes or court-ordered payments or if you attempt to make payments to a payee outside the U.S., bank and its agents will not be responsible for that payment.
By registering for the Bill Pay service, you authorize bank and its agents to follow the payment instructions you have provided using your Personal Internet Banking Account. You will provide bank with the names, addresses, phone numbers and account information of those persons or entities to whom you wish to make a Bill Payment. When you initiate a Bill Payment, you authorize bank to charge your account on a Business Day provided in the transaction and to remit funds to the payee on your behalf electronically, provided electronic payments are permitted and accepted by the payee. If the payee does not permit and accept electronic payments, then those funds will be remitted to the payee through the use of a paper check issued by bank or its agent and payable to the payee. Such paper check will state that it represents a payment from you and will indicate the account number of your account with the payee.
Payments can be sent to payees electronically or by check. As a number of different factors are considered to determine how the payment will be sent, we cannot tell which method of payment will be used until the payment is processed. Based on factors considered, our payment system selects the most appropriate method.
Electronic payments are sent whenever possible. If a payee accepts checks only, an individual corporate check is sent.<br/>
While it is anticipated that most Bill Payments will be processed and completed on the same business day selected for the Bill Payment Process Date, it is understood by you that due to circumstances beyond the control of bank, such as delays by the payee and the payee's bank or agent in handling and posting Bill Payments, some Bill Payments may take longer to be posted to your account at the payee. For this reason, bank recommends that you select a Bill Payment Process Date which is at least five Business Days before the actual due date of the payments. You agree that bank will not be responsible for any Bill Payment that is received or posted by the payee after the grace period or that results in a late charge or penalty being assessed by the payee if you did not follow this recommendation. In such event, you agree that you shall have the sole risk of incurring and the sole responsibility for paying any and all late charges or penalties assessed by the payee.
Only payees with United States addresses may be paid using the Bill Pay service. We reserve the right to limit the frequency and dollar amount of transactions from your accounts.
You may use Bill Pay service to authorize automatic recurring payments of recurring bills. These payments must be for the same amount each month and they will be paid on the same calendar day of each month, or on the next Business Day if the regular payment day falls on a weekend or holiday.
If a Bill Pay transaction cannot be processed according to your instruction, a BankMail notification will be sent to you.
Your Right to Cancel (Stop Payment) a Bill Payment<br/>
You can cancel or stop a single Bill Payment anytime before the Bill Payment Process Date for that payment through the use of Personal Internet Banking. If the Bill Payment is a recurring payment set up on the Bill Pay service, then you can cancel that Bill Payment: (1) Through the use of Personal Internet Banking as long as the request is received before the Bill Payment Process Date of the next recurring Bill Payment, (2) By calling us at 1-800-975-bank (1-800-975-4722), or (3) By writing to: bank Bank INDIA, National Association, PO Box 2013, Buffalo, NY 14240. We must receive your call or written request at least 3 (three) Business Days before the Bill Payment Process Date of the next recurring Bill Payment. If you call, we will require you to put your request in writing and get it to us within 14 calendar days after you have made the request. If you order us to cancel a recurring Bill Payment three Business Days before the Bill Payment Process Date of the next recurring Bill Payment and we do not do so, then we will be liable to you for your losses or damages. Once a recurring bill payment is cancelled, all future payments to that payee will be cancelled and you must reschedule it if you want a Bill Payment to be made in the future.
bank Mobile Banking<br/>
Mobile Banking is an extension of Personal Internet Banking and is available to all customers who have enrolled in the service. To use Mobile Banking customers are required to use their existing Personal Internet Banking log on credentials.
All features and services available through Personal Internet Banking are not available via Mobile Banking unless the Full Website option is launched from your mobile device.
You agree that you will not install software onto your mobile device that you are not familiar with or have not read the Terms and Conditions for that software.
You agree to download mobile security software updates when available. You agree that your mobile device will be locked if it is left unattended. As part of the security of your data, you must accept cookies. Cookies remind bank of your browser preferences and security requirements.
You agree to log off of Mobile Banking at the completion of your online session.
In the event that your mobile device is lost or stolen and you believe you were not logged off and / or feel your log on credentials may have been compromised, please contact the Customer Relationship Center. We also recommend that you contact your wireless service provider to have your device deactivated.
bank Bank INDIA, N.A. does not charge a fee for the using Mobile Banking. The usual and customary fees that the Bank may charge for any products and services provided continue to apply. You may incur internet data charges and call costs from your mobile service provider/internet service provider.
bank Money Management Tools (for Premier and Advance checking account customers)
The bank Money Management Tools (the "MM Tools") is a personal financial information management service that provides you with a dashboard tool to allow you to manage your financial information by consolidating it in one place on the Personal Internet Banking website. This service is only available to Advance and Premier checking account customers provided you fulfill all Premier or Advance proposition requirements as applicable. With the MM Tools, you may retrieve, view and organize information stored at various web sites you designate, all within one convenient service. All bank accounts linked to your username and log-on credentials through Personal Internet Banking from bank are automatically added to the MM Tools. These tools and services are currently free of charge. We reserve the right to charge fees for these services in the future. If you no longer meet the eligibility requirements for a Premier or Advance checking account, we reserve the right to withdraw access to the MM Tools, with or without notice.
1. Acceptance of Terms.
By using the information, tools, features and functionality of the MM Tools, you agree to be bound by these Terms. We reserve the right at our discretion to make changes to these terms in accordance with this Agreement. Also, when using services offered through your third party service providers, you will be subject to terms posted by your service providers. Use of their services, or acceptance of their terms of service, as the case may be, signifies your agreement to their terms and conditions of service. You may only use the MM Tools for personal or individual use. The MM Tools are not intended to provide legal, tax or financial advice. Data and information is provided for informational purposes only, and is not intended for trading or transactional purposes. You may not use the MM Tools on behalf of any business, partnership, corporation, proprietorship or other entity. You may not resell or otherwise provide other persons with access to these tools using your password or user names.
2. Third Party Accounts
By using the MM Tools, you authorize bank and its service providers to access third party sites designated by you, on your behalf, to retrieve information requested by you. You hereby authorize and permit bank and its service providers to use information submitted by you to the MM Tools (such as account passwords and users names) to accomplish the foregoing and to configure the MM Tools so that they are compatible with the third party sites for which you submit your information. You hereby represent to us that you are a legal owner of the accounts and have the authority to designate us as your agent, use these MM Tools and to give us your passwords, user names and all other information you provide. For all purposes hereof, you hereby grant bank and its service providers a limited power of attorney, and you hereby appoint us as your true and lawful attorney-in-fact and agent, with full power of substitution and re-substitution, for you and in your name, place and stead, in any and all capacities, to access third party sites, retrieve information, and use your information, all as described above, with the full power and authority to do and perform each and every act and thing requisite and necessary to be done in connection with such activities, as fully to all intents and purposes as you might or could do in person. YOU ACKNOWLEDGE AND AGREE THAT WHEN WE ARE ACCESSING AND RETRIEVING INFORMATION FROM THIRD PARTY SITES, WE ARE ACTING AS YOUR AGENT, AND NOT THE AGENT OR ON BEHALF OF THE THIRD PARTY. You agree that our service providers shall be entitled to rely on the foregoing authorization, agency and limited power of attorney granted by you, and our service providers are, for the purposes of this section, third party beneficiaries to this agreement, with the power to enforce these provisions as applicable. Third party web sites shall be entitled to rely on the above authorizations, agency and power of attorney granted by you.
The MM Tools do not have the capability to initiate transactions affecting your financial accounts or provide notices or instructions affecting such financial accounts. When you access a third party web site through the Tools, you open a new browser window to directly connect you to the third party web site and submit information you have designated to allow further access to that site. Transactions and inquiries you initiate at such a site are not made through the MM Tools, and we have no responsibility for such transactions. You are responsible for all fees charged by the third party in connection with such transactions and accounts, and you agree to comply with the terms and conditions of those accounts.
3. Rights You Grant to Us
A. Content You Provide.<br/>
Subject to our Privacy Notice, you are licensing to us any information, data, passwords, materials, or other content (collectively, "Content") you provide through or to us and the MM Tools. We may use, modify, display, distribute and create new material using such Content to provide the MM Tools to you. In addition, we may use this information to offer you other bank products and services that may be beneficial to you. By submitting Content, you automatically agree, or promise that the owner of such Content has expressly agreed that, without any particular time limit, and without the payment of any fees, we may use the Content for the purposes set out above. In addition, we welcome your feedback as a user of these tools. Any feedback you provide will become our confidential and proprietary information, and you agree that we may use in any manner and without limitation all comments, suggestions, complaints, and other feedback you provide relating to the MM Tools. We shall have a worldwide, royalty-free, non-exclusive, perpetual, and irrevocable right to use feedback for any purpose, including but not limited to, incorporation of such feedback into the MM Tools.
B. Registration for the Service.
By using Personal Internet Banking, you are automatically registered for the MM Tools and your bank Personal Internet Banking accounts will be pre-populated into the MM Tools, provided you fulfill all Premier or Advance proposition requirements as applicable, including but not limited to a Premier or Advance checking account. When you click on the "Launch Tools" button, you will have the option to also aggregate accounts to the MM Tools from other financial institutions. If you do not wish to have your external non-bank accounts included in the Money Management tools, you have the option to "Delete" them (permanently removes them from Money Management tools) or to Inactivate them (they will no longer be updated, but the history collected thus far will be retained should you decide to re-activate those accounts at some point in the future).
C. Account Access.
In order to ensure that we are able to provide a high quality service that is responsive to your needs, you agree that our employees, third party service providers, auditors, attorneys and other agents may have access to your account records as reasonably needed to investigate complaints or comply with applicable laws.
D. Advertising.<br/>
You agree that we may use your aggregated financial information to recommend products and services to you.
E. User Name and Password Privacy.
Our employees do not have access to your third party site usernames and passwords. Furthermore, no employee will ever be able to view or retrieve your password, except with your explicit permission as part of customer service efforts.
4. Permission To Access Your Account Information.
By aggregating accounts from other financial institutions to the MM Tools, you authorize and permit bank and its service providers to undertake the following actions on your behalf: access third party web sites, to retrieve your account and billing information, use information submitted by you to the MM Tools (such as account passwords and users names) and to configure the MM Tools so that they are compatible with the third party web sites for which you submit your information.
In order to provide you with the MM Tools, we must collect, on your behalf, your account and other personal information from third party web sites and other Internet services that you aggregate to the MM Tools.
We may disclose your name, user name, and user passwords that you provided during aggregation to third party web sites, so that the MM Tools can obtain the information you requested and display it to you on the MM Tools. When you add accounts for aggregation to the MM Tools, you authorize us and our service providers to disclose such information in order to provide the MM Tools.
You acknowledge and agree that for the limited purposes described in these terms, we shall be acting on your behalf and as your agent, and the acts undertaken by us to provide you with the MM Tools shall be deemed to be actions taken by you.
5. Third Party Sites.<br/>
You understand that we have no relationship, affiliation or connection with any third party web sites, including the web sites that are available for use with the MM Tools. The MM Tools are not endorsed or sponsored by the third party sites or any providers accessed in connection with the MM Tools. You agree that we assume no responsibility and shall incur no liability with respect to the acts, omissions or determinations of the third party web sites accessed in connection with the MM Tools. If you have a dispute or question about any transaction on such site, you agree to direct these to the account provider. Balances shown on the MM Tools reflect the most recent refresh and may not be accurate if a refresh was not successfully completed or the information obtained during the refresh from the third party is otherwise not accurate or current. You agree that we are not liable for any errors or delays in the content, or for any actions taken in reliance thereon. The third party institution you select is solely responsible for its services to you. We are not liable for any damages or costs of any type arising out of or in any way connected with your use of the services of a third party institution.
6. Provide Accurate Information.
You agree to provide true, accurate, current, and complete information about your accounts maintained at other web sites, as requested in our aggregation form and you agree to not misrepresent your account registration information. Accurate records enable us to provide the MM Tools to you. You agree to keep your account information up to date and accurate. Failure to provide accurate and complete information during aggregation may prohibit the use of the MM Tools. This aggregation information may include your passwords and user names for the third party web sites. We will have access to this information and use this information for providing the MM Tools and accessing web sites on your behalf.
7. Accessing Money Management Tools.<br/>
The MM Tools are accessible whenever you access your Personal Internet Banking account via computer, or compatible tablet or mobile devices, using your log on credentials. You are responsible for maintaining the confidentiality of your log-on credentials and following appropriate security measures when banking online. You are fully responsible for all activities that occur using your log-on credentials. Please notify us immediately of any unauthorized use of your log-on credentials or any other breach of security. We will not be liable for any loss that you may incur as a result of someone else using your log-on credentials, either with or without your knowledge. You may not use anyone else's password at any time. While the MM Tools are accessible on multiple devices (computer, tablet, and mobile), full functionality may not be available on tablet and mobile devices. You agree that you are solely responsible for any software requirements, including any applicable changes, updates and fees as well as the terms of your agreement with your mobile device and telecommunications provider. bank MAKES NO WARRANTIES OR REPRESENTATIONS OF ANY KIND, EXPRESS, STATUTORY OR IMPLIED AS TO: (i) THE AVAILABILITY OF TELECOMMUNICATION SERVICES FROM YOUR PROVIDER AND ACCESS TO THE SERVICES AT ANY TIME OR FROM ANY LOCATION; (ii) ANY LOSS, DAMAGE, OR OTHER SECURITY INTRUSION OF THE TELECOMMUNICATION SERVICES; AND (iii) ANY DISCLOSURE OF INFORMATION TO THIRD PARTIES OR FAILURE TO TRANSMIT ANY DATA, COMMUNICATIONS OR SETTINGS CONNECTED WITH THE SERVICES.
8. Service Limitations.
We will try very hard to make your experience with us a productive one. However, we cannot always foresee or anticipate technical or other difficulties. These difficulties may result in loss of data, personalization settings or other service interruptions. For this reason, you agree that our MM Tools are provided "AS IS", without warranties of any kind. We cannot assume responsibility for the timeliness, deletion, mis-delivery, or failure to store any user data, communications, or personalization settings.
9. Service Changes and Discontinuation.<br/>
We reserve the right to change or discontinue, temporarily or permanently, the MM Tools at any time without notice. You agree that we will not be liable to you or any third party for any modification or discontinuance of the MM Tools. We reserve the right to alter features, licensing terms, or other characteristics of any version of the MM Tools that it releases. We may suspend your access to the MM Tools at any time without notice and for any reasons, including but not limited to your non-use of the MM Tools or if you no longer meet the eligibility requirements to maintain a Premier or Advance checking account.
10. Privacy
We respect your privacy. The information you provide enables us to provide the MM Tools to you. It also enables us to give you updates about the MM Tools. You can see a full description of our privacy policies by clicking on the "Privacy" link located in the footer of the Personal Internet Banking web site.
The following information, in addition to our Privacy Notice, sets forth additional information regarding personal information that is collected through the MM Tools.
A. What categories of Personal Information does the MM Tools collect?
We collect the following categories of personal information about you through the MM Tools:
Information on Your Use of the Tools: We log information about your access and use of the tools, including (i) your transactions conducted in the tools, including through the use of Internet cookies (discussed below) (ii) the IP addresses from which you came to the site, and (iii) your communications with the MM Tools.
Information From Third Party Web Sites: In order to display information to you through the MM Tools, the MM Tools must collect, on your behalf, your account and other personal information from third party web sites and Internet services that you aggregate in the MM Tools. For example, if you aggregate your credit card account through the MM Tools, the MM Tools will collect the transactional and payment information regarding your credit card account to display it to you in the tools.
Account Access Information: Information may be required to utilize value-added features of the MM Tools, such as Auto-Registration, or to access specific third party Internet services using the MM Tools. This information may include your passwords and user names for the third party web sites and Internet services. We will use this information for providing the services and accessing the third party web sites you select on your behalf, so that we can present the requested information to you.
B. Does the Service use cookies?
The MM Tools store a non-persistent cookie ("session cookie") on your computer if you have cookies enabled. If you do not have cookies enabled, you will be unable to use the MM Tools. A session cookie is simply a text file, which contains session based information. The session cookie has a secure flag set which results in the cookie being transported through an encrypted SSL tunnel. This session cookie will only be returned to the server if your browser is set to allow sending of cookies (you can also set it to check for permission before sending cookies). We use session cookies for a variety of purposes intended to make the MM Tools a better service for you. For example, we use a session cookie to maintain session information for logged in users, to prevent the need for re-entry of login information when browsing outside the Tools. We reserve the right to use cookies to deliver content specific to your needs and interests. We may also use cookies to track user trends and patterns in order to better understand and improve areas of our sites that our users find valuable. We reserve the right to use outside ad companies to display ads on our sites. These ads may contain cookies. Cookies received with banner ads are collected by our ad companies, and we do not have access to this information.
11. Obey the Law.<br/>
You agree not to use the MM Tools for illegal purposes or for the transmission of material that is unlawful, harassing, libelous (untrue and damaging to others) invasive of another's privacy, abusive, threatening, or obscene, or that infringes the rights of others.
12. Proprietary Rights.
You acknowledge and agree that we, our service providers and/or our licensors or suppliers own all rights to these MM Tools, the content displayed on the service and any intellectual or proprietary property and/or technology (in any form) made available to you as a part of or in conjunction with the MM Tools. You are only permitted to use any the foregoing as expressly authorized by these Terms and otherwise by the MM Tools. You may not copy, reproduce, distribute, or create derivative works from any content. If you access Zillow content, you agree that you will not use Zillow data for any other purpose than for your individual use. Further, you agree not to reverse engineer or reverse compile any technology associated with the MM Tools, including but not limited to, any software applications or Java applets associated with the MM Tools. Your right to use the MM Tools is personal to you; therefore, you agree not to resell or make any commercial use of the MM Tools.
13. Categorization of Transactions, Accounts or Other Information.
The categorization in the MM Tools is an estimated categorization provided for your information only, and does not indicate accurate status of any transaction, account or other information. You agree that you will not rely on the categories provided in or set by you for any purpose, including without limitation, for tax deductions.
14. Other Important Legal Matters<br/>
DISCLAIMER OF WARRANTIES. YOU EXPRESSLY UNDERSTAND AND AGREE THAT: YOUR USE OF THE TOOLS AND ALL INFORMATION, PRODUCTS AND OTHER CONTENT (INCLUDING THAT OF THIRD PARTIES) INCLUDED IN OR ACCESSIBLE FROM THE TOOLS IS AT YOUR SOLE RISK. THE TOOLS ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. bank AND ITS AGENTS, LICENSORS, DISTRIBUTORS, ADVERTISERS, DEALERS AND SUPPLIERS EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND AS TO THE TOOLS AND ALL INFORMATION, PRODUCTS AND OTHER CONTENT (INCLUDING THAT OF THIRD PARTIES) INCLUDED IN OR ACCESSIBLE FROM THE TOOLS, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, WE ARE NOT RESPONSIBLE FOR THE ACCURACY OR RELIABILITY OF ANY DATA FROM ANY THIRD PARTY OR FOR ANY INTERRUPTIONS IN THE AVAILIABILITY OF ANY SERVICE, WHETHER THE RESULT OF ACTIONS BY US OR ANY THIRD PARTY. CATEGORIZATION WITHIN THE TOOLS IS AN ESTIMATION PROVIDED FOR YOUR INFORMATION ONLY, AND WE DISCLAIM ALL WARRANTIES OF ACCURACY FOR ANY USE, INCLUDING WITHOUT LIMITATION, TAX DEDUCTION CATEGORIZATION. bank AND ITS SERVICE PROVIDERS, AGENTS, LICENSORS, DISTRIBUTORS, ADVERTISERS, DEALERS AND SUPPLIERS MAKE NO WARRANTY THAT (i) THE TOOLS WILL MEET YOUR REQUIREMENTS, (ii) THE TOOLS WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (iii) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE TOOLS WILL BE ACCURATE OR RELIABLE, (iv) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE TOOLS WILL MEET YOUR EXPECTATIONS, AND (v) ANY ERRORS IN THE TECHNOLOGY WILL BE CORRECTED. ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE TOOLS IS DONE AT YOUR OWN DISCRETION AND RISK AND YOU ARE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM US OR THROUGH OR FROM THE TOOLS WILL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THESE TERMS. Some jurisdictions do not allow the exclusion of certain warranties. Accordingly, some of the above limitations may not apply to you. TO THE EXTENT THAT ANY PART OF THIS SECTION IS NOT CONSISTENT WITH ANY OTHER PART OF THESE TERMS, THEN THIS SECTION WILL CONTROL.
Third Party Products and Services. We remind you to be cautious when browsing on the Internet and to use good judgment and discretion when making purchases, obtaining information, or transmitting information. From these tools, you may visit or be directed to sites containing information or material that may be offensive or inappropriate to some people. bank makes no effort to review the content of these sites, nor is bank, or its agents, licensors, distributors, advertisers, dealers and suppliers responsible for the validity, legality, copyright compliance, or decency of the content contained in these sites. In addition, bank does not endorse or control the content of any other user and is not responsible or liable for any content, even though it could be unlawful, harassing, libelous, privacy invading, abusive, threatening, harmful, vulgar obscene or otherwise objectionable, or that it infringes or may infringe upon the intellectual property or other rights of another. You acknowledge that bank does not pre-screen content, but that bank, and its agents, licensors, distributors, advertisers, dealers and suppliers will have the right (but not the obligation) in their sole discretion to refuse, edit, move or remove any content that is available via the MM Tools.
LIMITATION OF LIABILITY. YOU AGREE THAT NEITHER bank, NOR ANY OF ITS AFFILIATES, SUBSIDIARIES, LICENSORS, SUPPLIERS, ACCOUNT PROVIDERS, SERVICE PROVIDERS OR ANY OF THEIR AFFILIATES WILL BE LIABLE FOR ANY HARMS, WHICH LAWYERS AND COURTS OFTEN CALL DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, OPPORTUNITY, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES, EVEN IF bank HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THE TOOLS; (ii) THE COST OF GETTING SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY PRODUCTS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO, THROUGH OR FROM THE TOOLS; (iii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (iv) STATEMENTS OR CONDUCT OF ANYONE ON THE TOOLS; (v) THE USE, INABILITY TO USE, UNAUTHORIZED USE, PERFORMANCE OR NON-PERFORMANCE OF ANY THIRD PARTY ACCOUNT PROVIDER SITE, EVEN IF THE PROVIDER HAS BEEN ADVISED PREVIOUSLY OF THE POSSIBILITY OF SUCH DAMAGES; OR (vi) ANY OTHER MATTER RELATING TO THE TOOLS. Some jurisdictions do not allow the limitation or exclusion of liability for incidental or consequential damages. Accordingly, some of the above limitations may not apply to you.
Indemnification. You agree to protect and fully compensate bank and its affiliates, subsidiaries, licensors, suppliers and service providers from any and all third party claims, liability, damages, expenses and costs (including, but not limited to, reasonable attorneys fees) caused by or arising from your use of the MM Tools, your violation of the Terms or your infringement, or infringement by any other user of your account, of any intellectual property or other right of anyone.
Potential Risks. While you may decide to aggregate accounts to this service from other financial institutions, we want you to know some potential risks. Aggregating accounts to the MM Tools will require that you provide authentication information for your various on-line services. Although every precaution has been taken to offer the MM Tools using state-of-the-art security measures, there is a risk of unauthorized access to your personal information if you fail to exercise adequate controls over your login information. Your aggregation to the MM Tools acknowledges that this risk exists and that bank is not liable to you for any harm or damage that may occur. You acknowledge and agree that we may not maintain the same level of security against unauthorized access to your account information as the third party sites from which you authorize us to retrieve information on your behalf.
Bank to Bank Transfers Service<br/>
Bank to Bank Transfers ("Service") offered by bank and service provider allows you to transfer funds to or from your bank accounts and any other account held by you at another U.S. financial institution – referred to in these terms as 'Accounts' – assuming, of course, that the transfer is permitted by your financial institution and by law. Bank to Bank Transfers can only be completed between accounts that are owned by the same account holder. In order to use Bank to Bank Transfers, you have to be a Personal Internet Banking ("Personal Internet Banking") customer of bank. Details of applicable limits can be found on the Bank to Bank Transfers section of the website.
1. Acceptance of Bank to Bank Transfers Terms
These terms apply when you use Bank to Bank Transfers. bank reserves the right to change the Terms under which the Service is offered in its sole discretion at any time; however, bank will notify you of any material change to the Terms. In most cases, you will receive the notice online the next time you log in; however, bank reserves the right to notify you by email or by conventional mail, at its discretion. You agree that if you continue to use the Service after we notify you of any change, you thereby accept the changes to the Terms and agree to be bound by this Agreement, as amended. If you do not accept and agree to the changes to the Terms, you will not be entitled to use the Service. You can review, download and print the most current version of this Agreement at any time by clicking on the Terms and Conditions link within the footer of the Personal Internet Banking web site and then clicking "Personal Internet Banking" in the "Other Terms & Conditions" section of the right hand menu. If you do not agree to the changes, or if at any time you wish to discontinue your use of the Service, you can unsubscribe by sending a secure 'BankMail' from Internet Banking or call our Customer Relationship Center at 1-800-975-bank (1-800-975-4722), to unsubscribe from the service. Representatives are available Monday - Sunday 7:00am - 12:00am ET and will be happy to help.
2. Information Authorization
bank and our service provider reserve the right to obtain such additional information as we deem reasonably necessary to insure that you are not using our Service in violation of law, including, but not limited to, laws and regulations designed to prevent 'money laundering' or the transfer of funds to accounts that are blocked under regulations of the Office of Foreign Assets Control (OFAC) of the United States Treasury Department.
Once you are approved for Bank to Bank Transfers, we may verify the Accounts that you add to the Service from time to time. You authorize us to validate the Accounts through the use of a test transfer, in which one or more low value payments will be both credited to and debited from the Account. The test credit will always occur before the test debit and will always be of the same or lesser amount, so that the balance in any of your Accounts will never be less than the actual balance.
Once the test transfer is complete, we may ask you to access your Account to tell us the amount of the test credit or debit or any additional information reported by your bank with this test transfer. We may also verify Accounts by requiring the entry of information you ordinarily use to access the Account provider's web site, or by requiring you to submit proof of ownership of the Account.
3. User Content<br/>
Subject to bank's Privacy Policy, you agree that bank may use, copy, modify, display and distribute any information, data, materials or other content (the "Content") you provide to bank for the purpose of providing the Service, and you hereby give bank a license to do so. By submitting Content, you represent that you have the right to license such Content to bank for the purposes set forth in this Agreement.
4. Accounts
You understand that in order to complete Bank to Bank Transfers, it is necessary for bank and our service provider to access the websites and databases of your bank and other institutions where you hold Accounts, as designated by you and on your behalf, to retrieve information and effect the fund transfers you request. By using the Service, you represent and warrant to us that you have the right to authorize and permit us to access your Accounts to effect such funds transfers or for any other purpose authorized by this Agreement, and you assure us that by disclosing and authorizing us to use such information you are not violating any third party rights. You warrant and represent that the information you are providing us with is true, current, correct and complete. You hereby authorize and permit bank and our service provider to use information submitted by you to accomplish these purposes and to configure the Service to be compatible with the Accounts.
For as long as you are using the Service, you give to bank and our service provider a limited power of attorney and appoint bank and our service provider as your true and lawful attorney-in-fact and agent, with full power of substitution and resubstitution, for you and in your name, place and stead, in any and all capacities, to access the Accounts, effect funds transfers as described above, with full power and authority to do and perform each and every act and thing requisite and necessary to be done in connection with effecting funds transfers, including verifying the content and authenticity of any funds transfer instruction for the purposes of security procedures applicable to Accounts, as fully to all intents and purposes as you might or could in person. Once bank and/or our service provider has actual knowledge that you wish to cease using the Bank to Bank Transfers service as provided in this Agreement or as otherwise permitted in this Agreement and has a reasonable opportunity to act on such knowledge, this limited power of attorney is automatically revoked; provided, however, that any act done by bank and/or our service provider in good faith before it has actual knowledge of termination by you and has a reasonable opportunity to act on such knowledge shall be deemed to be authorized by you.
You understand and agree that at all times your relationship with each Account provider is independent of bank and your use of the Bank to Bank Transfers. bank will not be responsible for any acts or omissions by the financial institution or other provider of any Account, including without limitation any modification, interruption or discontinuance of any Account by such provider.
YOU ACKNOWLEDGE AND AGREE THAT WHEN bank AND OUR SERVICE PROVIDER IS EFFECTING A BANK TO BANK TRANSFER FROM OR TO ANY OF YOUR ACCOUNTS, bank AND OUR SERVICE PROVIDER IS ACTING AS YOUR AGENT, AND NOT AS THE AGENT OR ON BEHALF OF ANY THIRD PARTY. You agree that bank, its affiliates, service providers and partners shall be entitled to rely on the foregoing authorization, agency and power of attorney granted by you.
YOU AGREE THAT WE SHALL NOT BE LIABLE FOR ANY COSTS, FEES, LOSSES OR DAMAGES OF ANY KIND INCURRED AS A RESULT OF (1) OUR ACCESS TO THE ACCOUNTS; (2) OUR DEBIT AND/OR CREDIT OR INABILITY TO DEBIT AND/OR CREDIT THE ACCOUNTS IN ACCORDANCE WITH YOUR BANK TO BANK TRANSFERS INSTRUCTIONS; (3) ANY INACCURACY, INCOMPLETENESS OR MISINFORMATION CONTAINED IN THE INFORMATION RETRIEVED FROM THE ACCOUNTS; (4) ANY CHARGES IMPOSED BY ANY PROVIDER OF ACCOUNTS AND (5) ANY FUNDS TRANSFER LIMITATIONS SET BY THE FINANCIAL INSTITUTIONS OR OTHER PROVIDERS OF THE ACCOUNTS.
Not all types of accounts are eligible for the Bank to Bank Transfers service. Bank to Bank Transfers allows personal accounts in your name to be added to your profile. Business accounts are not eligible to be used with the Bank to Bank Transfers service. Be sure to check with your financial institution for restrictions regarding transfers among your retirement (401k, IRA, etc.), savings, trusts, loans, custodial, and other account types. We are not responsible for any costs or losses incurred from Bank to Bank Transfers that are not permitted under such restrictions by the provider of your Account or those imposed by applicable law.
5. Electronic Communications<br/>
A. General Consent; Categories of Records.
Bank to Bank Transfers is an electronic, Internet-based service. Therefore, you understand and agree that this Agreement will be entered into electronically, and that the following categories of information ("Communications") may be provided by electronic means:
This Agreement and any amendments, modifications or supplements to it.
Your records of Bank to Bank Transfers and other transactions through the Service, including without limitation confirmations of individual transactions.
Any initial, periodic or other disclosures or notices provided in connection with the Service, including without limitation those required by federal or state law.
Any customer service communications, including without limitation communications with respect to claims of error or unauthorized use of the Service.
Any other communication related to the Service.
Although bank reserves the right to provide Communications in paper format at any time, you agree that we are under no obligation to do so. All Communications in either electronic or paper format will be considered to be "in writing." You should print a paper copy of this Agreement and any electronic Communication that is important to you and retain the copy for your records. If you do not agree to receive this Agreement or the Communications electronically, you may not use the Service.
B. How to Withdraw Consent.<br/>
If you have registered for the Service and you wish to withdraw your consent to have Communications provided in electronic form, you must cancel any pending transfer requests (within the time period permitted by the Service cancellation policies) and stop using the Service.
C. How to Update Your Records.
You agree to promptly update your registration records if your email address or other information changes. You may update your records, such as your email address, by using the Customer Service page in Personal Internet Banking.
D. Delivery of Electronic Communications.
Communications may be posted on the pages of the Service website or other website disclosed to you and/or delivered to the email address you provide. Any electronic Communication sent by email will be deemed to have been received by you when bank sends it to you, whether or not you received the email. If the Communication is posted on the Service, then it will be deemed to have been received by you no later than five (5) business days after bank posts the Communication on the pages of the Service, whether or not you retrieve the Communication. An electronic Communication by email is considered to be sent at the time that it is directed by bank's email server to the appropriate email address. An electronic Communication made by posting to the pages of the Service is considered to be sent at the time it is publicly available. You agree that these are reasonable procedures for sending and receiving electronic Communications.
E. Email Requirements.<br/>
In order to access and retain Communications, you must have:
An email account and email software capable of reading your email.
6. Privacy Policy and Confidentiality
In order to provide Bank to Bank Transfers, we must obtain from you certain personal information about you, your Accounts, and your transactions (referred to herein as "User Information"). You represent that you have the right to provide such User Information and that you give us the right to use the User Information.
You can see a full description of our privacy policy by clicking on the "Privacy" located in the footer of the Personal Internet Banking web site.
7. Business Days
The Service will process requests for transfers on business days. The business days for Bank to Bank Transfers are Monday through Friday. Federal Reserve Bank Holidays are not included.
8. Transfer Types and Limitations
A. Types of Transfers
You may use this service to transfer funds to or from an bank account and another personal account in your name at another U.S. financial institution or an approved service provider investment account via the web. Transactions may be scheduled to occur one time, for a future date, or recurring.
Some of these services may not be available at all times. We may from time to time make available additional or new features to the Service, including but not limited to, a next day service and a higher limit service. You will be approved or declined for any such additional service at our sole discretion and additional terms and conditions may apply. Please ensure that you have sufficient funds to effect any Bank to Bank Transfers from your Accounts. We may at any time decline to effect any Bank to Bank Transfer that we believe may violate applicable law.
B. Dollar Amount of Transfers
You may not make Bank to Bank Transfers in excess of limits described on the Service. We reserve the right to change from time to time the dollar amount of the Bank to Bank Transfers you are permitted to make using our Service. Without limiting the foregoing, in the event that your use of the Service has been suspended and reinstated as provided herein (see "Suspension and Reinstatement of Bank to Bank Transfers" below), you understand and agree that your use of the Service thereafter may be subject to lower dollar amount limitations than would otherwise be permitted by us.
C. Transfers Subject to the Rules of the Accounts
Additionally, all Bank to Bank Transfers are also subject to the rules and regulations governing the relevant Accounts. You agree not to effect any Bank to Bank Transfers from or to an Account that are not allowed under the rules or regulations applicable to such accounts including, without limitation, rules or regulations designed to prevent the transfer of funds in violation of OFAC regulations.
9. Rejection of Transfers<br/>
We reserve the right to decline to effect any Bank to Bank Transfer, to submit Bank to Bank Transfer instructions or orders or to carry out change or cancellation requests.
10. Authorization
You authorize us to select any means to execute your Bank to Bank Transfer instructions. You understand that to effect your Bank to Bank Transfer instruction we utilize the Automated Clearing House (ACH), using applicable ACH Rules, we debit one of your Accounts and credit another of your Accounts. Once your Account has been debited, we credit our service provider's transfer account at the service provider's clearing bank. After our service provider and/or its clearing bank are reasonably certain that the debit will not be returned (in most cases this is usually between 3-4 banking days), our service provider will credit your Account. The sole purpose for our service provider's transfer account is to complete your Bank to Bank Transfer requests and for performing the services within the scope of this Agreement. The service provider earns no interest on the funds in the transfer account. If the debit side fails or is returned for any reason and the credit side has been released and cannot be collected, you authorize our service provider to collect from the Account to which the credit side of the funds transfer was sent. We reserve the right to resubmit a debit, or a portion of the debit, in the event of an insufficient or uncollected funds return and if we cannot collect the amount credited. To effect this collection, you understand and authorize us to debit the credited Account or the debited Account in either the same dollar amount as the original funds transfer or a portion of the debit. There may be a fee associated with such collection imposed by the financial institution holding the Account.
You understand and agree that we may from time to time impose additional charges in connection with your Bank to Bank Transfers transactions. bank will notify you of such fee in advance of the transaction and according to applicable rules and regulations. If you choose to proceed with the transaction, you authorize bank to debit your account in the amount indicated.
In the event that a debit to any of your Accounts, or any portion of any such debit, has failed and the credit side of such transaction has been released and cannot be collected, and we are unable to debit either the debited or the credited Account as set forth above, we reserve the right, and you hereby authorize us, to debit any of your other Accounts to the extent necessary to offset any resulting deficiency. We do not undertake to notify you in such event, other than by posting any such transfer or transfers to the applicable Account in accordance with this Agreement.
You understand and agree that in the event we are unable to execute your Bank to Bank Transfers request utilizing the ACH, we may utilize other established payment mechanisms in order to complete your funds transfer instructions, such as wire transfer or check.
11. Suspension and Reinstatement of Bank to Bank Transfers
In the event that we at any time incur a problem with your use of the Service, including without limitation a failure in attempting to debit any of your Accounts or to collect with respect to any of your Bank to Bank Transfers as described above, and without limiting any other right or remedy that we may have under this Agreement or otherwise, we reserve the right to suspend your right to use the Service, immediately and without prior notice to you. You understand and agree that such action is reasonable for us to take in order to protect itself from loss. In the event of such suspension, you may request reinstatement of your service by contacting us using any of the methods provided for under this Agreement (see "Error Reporting and Claims," below). We reserve the right in our sole discretion to grant or deny reinstatement of your use of the Service. In the event we agree to reinstate you, we reserve the right to, and ordinarily will, initially reinstate your Service subject to lower per-transaction and monthly dollar limits and/or with other restrictions than otherwise might be available to you. Based upon your subsequent usage of the Service, bank in its sole discretion may thereafter restore your ability to effect transfers subject to such higher limits as may then be in effect (see "Dollar Amount of Transfers," above).
12. Documentation<br/>
You may access a statement of all Bank to Bank Transfers effected or pending at any time by clicking on the 'History' tab located within the Bank to Bank Transfers service. If a Bank to Bank Transfer could not be completed, bank and/or our service provider, upon learning that the Bank to Bank Transfer has failed, will make a reasonable effort to complete the transfer. If the Bank to Bank Transfer fails a second time, we will notify you to contact your financial institution or other provider of the relevant Account to learn more about the failure.
13. Your Responsibility for Errors
You understand that we must rely on the information provided by you and you authorize us to act on any instruction which has been or reasonably appears to have been sent by you, to submit Bank to Bank Transfer instructions on your behalf. You understand that financial institutions receiving the Bank to Bank Transfer instructions may rely on such information. We are not obliged to take any further steps to confirm or authenticate such instructions and will act on them without getting further confirmation. You understand that if you provide us with incorrect information or if there is any error in your instruction we will make all reasonable efforts to reverse or delete such instructions, but you accept full responsibility for losses resulting from any of your errors, duplication, ambiguities or fraud in the information that you provide. You agree not to impersonate any person or use a name that you are not authorized to use. If any information you provide is untrue, inaccurate, not current or incomplete, without limiting other remedies, bank reserves the right to recover from you any costs or losses incurred as a direct or indirect result of the inaccurate or incomplete information.
14. Error Reporting and Claims
For Error Resolution procedures concerning your personal bank accounts, you may refer to the Personal Internet Banking Terms and Conditions at any time by clicking on the Terms and Conditions link within the footer of the Personal Internet Banking web site and then clicking "Personal Internet Banking" in the "Other Terms & Conditions" section of the right hand menu. We are not responsible for errors, delays and other problems caused by or resulting from the action or inaction of financial institutions holding the Account. Although we will try to assist you in resolving any such problems, you understand that any such errors, delays or other problems are the responsibility of the relevant financial institution. Any rights you may have against a financial institution for such errors, delays or other problems are subject to the terms of the agreements you have with such financial institution, including any time limits during which complaints must be made.
15. Proprietary Rights
You acknowledge and agree that bank and/or our service provider own all rights in and to the Bank to Bank Transfers. You are permitted to use the Service only as expressly authorized by this Agreement. You may not copy, reproduce, distribute, or create derivative works, reverse engineer or reverse compile bank and/or our service provider's Bank to Bank Transfers or any of bank's and/or our service provider's services or technology.
16. No Unlawful or Prohibited Use
As a condition of using the Service, you warrant to us that you will not use the Service for any purpose that is unlawful or is not permitted, expressly or implicitly, by the terms of this Agreement or by any applicable law or regulation. You further warrant and represent that you will not use the Service in any manner that could damage, disable, overburden, or impair the Service or interfere with any other party's use and enjoyment of the Service. You may not obtain or attempt to obtain any materials or information through any means not intentionally made available or provided for through the Service. You agree that these warranties and representations will remain in full force and effect even if this Agreement terminates for any reason.
17. Service Changes and Discontinuation
We may modify or discontinue the Service or your use of the some or all accounts within the service, with or without notice, without liability to you, any other user or any third party. We reserve the right, subject to applicable law, to terminate your account within the Service and your right to use the Service at any time and for any reason, including without limitation if we, in our sole judgment, believe you have engaged in conduct or activities that violate any of the Terms or the rights of bank and/or our service provider, or if you provide us with false or misleading information or interfere with other users or the administration of the Services. We reserve the right to charge a fee for the use of the Service and any additional services or features that we may introduce. You understand and agree that you are responsible for paying all fees associated with the use of our Bank to Bank Transfers.
You can terminate your Bank to Bank Transfer service with bank at any time by clicking on "Remove Bank to Bank Transfers" located under 'Customer Service' in the Personal Internet Banking left hand navigation. You can also send a secure 'BankMail' from Internet Banking or call our Customer Relationship Center at 1-800-975-bank (1-800-975-4722), to unsubscribe from this service. Representatives are available Monday - Sunday 7:00am - 12:00am ET and will be happy to help.
18. Service Charges
There are no transaction fees when you transfer funds via the Bank to Bank Transfer service.
19. Security Procedures
You understand that the financial institution at which an Account is maintained may contact us to verify the content and authority of Bank to Bank Transfer instructions and any changes to those instructions. You understand that, as your agent, we may provide to such financial institution such information as may be required to verify the instructions and may constitute a valid security procedure under the rules governing such Account.
20. Deviating from Security Procedures
You agree to allow us to authorize any financial institution at which you have an Account to accept funds and transfer instructions in accordance with any authorization procedures as may be agreed from time to time between you and such financial institution, or between us, on your behalf, and such financial institution, without verifying the instructions under the established security procedures, regardless of whether such security procedures were agreed by you directly or by us on your behalf. In addition you agree that we may authorize such financial institutions to charge and debit your accounts based solely on these communications.
21. Account Number Policy
If Bank to Bank Transfer instructions identify a bank or beneficiary by name and account number, the relevant financial institution may execute those instructions by reference to the number only, even if the number does not correspond to the name. You understand that such financial institutions may not investigate discrepancies between names and numbers. In addition, you agree that we have no responsibility to investigate discrepancies between names and numbers.<br/>
22. Joint Account Holder
By using Bank to Bank Transfers, you confirm that, if any of your Accounts is a joint account, your joint account holder has consented for you to use your Accounts for the Service. We will end your use of the Service if any joint account holder notifies us that (i) they never consented to your use of our Bank to Bank Transfers service, (ii) the joint account can no longer be operated on your instructions alone, or (iii) they are withdrawing consent for you to operate the joint account.
23. Means of Transfer
You authorize us to select any means we deem suitable to provide your Bank to Bank Transfer instructions to the applicable financial institution. These choices include banking channels, electronic networks, and funds transfer systems. You agree to be bound by the rules and regulations that govern the applicable funds transfer systems, such as automated clearinghouse (ACH) as published by the National Automated Clearinghouse Association (NACHA). We shall make all reasonable efforts to ensure that your transfer requests are processed on time; however, we reserve the right to hold funds beyond the normal period and if any interest is earned will be the property of bank.
24. Our Liability
If we do not provide a funds transfer instruction on time, if we cause an incorrect amount to be removed from an Account or if we cause funds from an Account to be transferred to any account other than the Account specified in the applicable funds transfer instruction, we shall be responsible for returning the improperly transferred funds and/or for directing any misdirected funds to the proper Account. bank is not responsible or liable if your financial institution's system fails and we are unable to complete the transfer. Except as otherwise required by law, bank shall in no other event be liable for any losses and damages other than those arising from gross negligence or willful misconduct on our part or if we breach a representation or warranty of bank hereunder.
You agree that your transfer instructions constitute authorization for us to complete the transfer. You represent and warrant to us that you have enough money in the applicable Accounts to make any Bank to Bank Transfer you request that we make on your behalf through the Service. You understand and agree that we are not liable under any circumstances for any losses or damages if, through no fault of ours, you do not have enough money to make the Bank to Bank Transfer and the Bank to Bank Transfer is not completed or is later reversed or if your financial institution does not permit the transfer or the Bank to Bank Transfer would exceed the credit limit on any applicable overdraft line.
You also understand and agree that we are not responsible for any losses or damages if circumstances beyond our control (such as fire or flood) prevent us from making a Bank to Bank Transfer or if the bank website was not working properly and you knew about the breakdown when you started the Bank to Bank Transfer.
25. Your Right to Cancel a Bank to Bank Transfer
You can cancel or stop a single Bank to Bank Transfer anytime before the debit transaction is sent to the Federal Reserve Bank through the Bank to Bank Transfers service via Personal Internet Banking. If the transfer is a recurring transfer set up on the Bank to Bank Transfers service, then you can cancel that Transfer through the use of ‘Bank to Bank Transfers’ via Personal Internet Banking as long as the request is received before the Process Date of the next recurring transfer. Once a recurring transfer is cancelled, all future transfers will be cancelled and you must reschedule it if you want transfers to be made in the future.
26. Limitation of Warranty and Liability
YOU UNDERSTAND AND AGREE THAT OUR BANK TO BANK TRANSFERS SERVICE IS PROVIDED "AS-IS." EXCEPT AS OTHERWISE PROVIDED IN THIS AGREEMENT OR AS REQUIRED BY LAW, WE ASSUME NO RESPONSIBILITY FOR THE TIMELINESS, DELETION, MIS-DELIVERY OR FAILURE TO STORE ANY USER COMMUNICATIONS OR PERSONALIZATION SETTINGS. YOU UNDERSTAND AND EXPRESSLY AGREE THAT USE OF THE BANK TO BANK TRANSFERS SERVICE IS AT YOUR SOLE RISK, THAT ANY MATERIAL AND/OR DATA DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE BANK TO BANK TRANSFERS SERVICE IS DOWNLOADED OR OBTAINED AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OR THE OBTAINING OF SUCH MATERIAL AND/OR DATA.
EXCEPT AS EXPRESSLY SET FORTH ON THE bank WEB SITE OR IN THIS AGREEMENT, WE DISCLAIM ALL WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT OF INTELLECTUAL PROPERTY OR THIRD PARTY RIGHTS, AND WE MAKE NO WARRANTY OR REPRESENTATION REGARDING THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE BANK TO BANK TRANSFERS SERVICE, THE ACCURACY OR RELIABILITY OF ANY INFORMATION OBTAINED THROUGH THE BANK TO BANK TRANSFERS SERVICE, THE ACCURACY OF ANY INFORMATION RETRIEVED BY US FROM THE ACCOUNTS OR THAT THE BANK TO BANK TRANSFERS SERVICE WILL MEET ANY USER'S REQUIREMENTS, BE UNINTERRUPTED, TIMELY, SECURE OR ERROR FREE.
EXCEPT AS DESCRIBED IN THIS AGREEMENT, WE WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES OF ANY KIND RESULTING FROM THE USE OF OR THE INABILITY TO USE THE BANK TO BANK TRANSFERS SERVICE, ANY INACCURACY OF ANY INFORMATION OR AMOUNT RETRIEVED BY US FROM THE ACCOUNTS, ANY BREACH OF SECURITY CAUSED BY A THIRD PARTY, ANY TRANSACTIONS ENTERED INTO BASED ON THE BANK TO BANK TRANSFERS SERVICE, ANY LOSS OF, UNAUTHORIZED ACCESS TO OR ALTERATION OF A USER'S TRANSMISSIONS OR DATA OR FOR THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF PROFITS, USE, DATA OR OTHER INTANGIBLES, EVEN IF WE HAD BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
27. Indemnification<br/>
You agree to indemnify, defend and hold harmless bank, its service provider, its affiliates, partners, officers, directors, employees, consultants, service providers and agents from any and all third party claims, liability, damages and/or costs (including, but not limited to, attorneys' fees) arising from your use of the Bank to Bank Transfers service, our reliance on the information, instruction, license and/or authorization provided by you under or pursuant to this Agreement, your violation of the Terms or your infringement, or infringement by any other user of your Accounts, of any intellectual property or other right of any person or entity.
28. Miscellaneous
You understand and agree that our service provider is not a bank, a broker-dealer firm, or any other kind of financial institution. You represent and warrant that you are who you claim to be; that you are the rightful owner of all Content and the Accounts linked for the purposes of the Bank to Bank Transfers; and that you are rightfully authorizing us to access the Accounts.
You agree that our rights and remedies arising out of any breach of your representations and warranties in this Agreement, the limitations on our liability and our rights to indemnification under this Agreement are continuing and shall survive the termination of this Agreement, notwithstanding the lack of any specific reference to such survivability in these provisions. bank's failure to enforce the strict performance of any provision of this Agreement will not constitute a waiver of bank's right to subsequently enforce such provision or any other provisions of this Agreement.
The most current version of this Agreement as it appears on our website, including any amendments that we may make from time to time, constitutes the entire agreement between us, and supersedes and replaces all other agreements or understandings, whether written or oral, regarding the Bank to Bank Transfers service. This Agreement may be amended, or any of bank's rights waived, only if bank agrees in writing to such changes, or you continue using the Bank to Bank Transfers service following receipt of notice of any changes proposed by bank. All notices to you shall be in writing and shall be made either via email, conventional mail or messages delivered through the Services, at bank's discretion. All notices to bank must be made in writing and sent to bank via registered or certified mail.
bank Bank INDIA, N.A.
P.O. Box 2013
Buffalo, NY 14240<br/>
This Service and these Terms are personal to you and may not be assigned to anyone by you.
If either of us has any dispute or disagreement with the other regarding this Service that we cannot resolve amicably, both parties agree that the sole and exclusive remedy shall be binding arbitration in accordance with the then-current rules and procedures of the American Arbitration Association. This Service shall be governed by and construed in accordance with the laws of the State of New York, without giving effect to its conflict of laws provisions or your actual state or country of residence. If for any reason a court of competent jurisdiction finds any provision or portion of the Terms to be unenforceable, the remainder of the Terms will continue in full force and effect.
Electronic Funds Transfer Provisions for Consumers
The provisions in this section apply only to electronic funds transfers that debit or credit a consumer's checking, savings or other asset account and are subject to the Federal Reserve Board's Regulation E (an 'EFT'). bank may rely on any exceptions to the provisions in this section that are contained in Regulation E. All terms not otherwise defined in these Terms and Conditions which are defined in Regulation E will have the same meanings when used in this section as they do in Regulation E.
Your liability for an unauthorized EFT or a series of related unauthorized EFTs will be determined as follows:
If you notify us within two business days after learning of the loss or theft of your log on credentials, your liability will not exceed the lesser of $50 or the amount of unauthorized EFTs that occur before notice to us.
If you fail to notify us within two business days after learning of the loss or theft of your log on credentials, your liability will not exceed the lesser of $500 or the sum of:
$50 or the amount of unauthorized EFTs that occur within the two business days, whichever is less; and
The amount of unauthorized EFTs that occur after the close of two business days and before notice to us, provided we establish that these EFTs would not have occurred had you notified us within that two-day period.
You must report an unauthorized EFT that appears on a periodic statement within 60 days of our transmittal of the statement to avoid liability for subsequent transfers. If you fail to do so, your liability will not exceed the amount of the unauthorized EFTs that occur after the close of the 60 days and before notice to us, and that we establish that they would not have occurred had you notified us within the 60-day period. You may, as applicable, also be liable for the amounts described in the two immediately preceding paragraphs.
If your delay in notifying us was due to extenuating circumstances, we will extend the times specified in the three immediately preceding paragraphs to a reasonable period.
Telephone Number and Addresses
The telephone number and address to be used to notify bank when you believe that an unauthorized EFT has been or may be made are:
Customer Service at 1-800-975-bank (1-800-975-4722) (24 hours a day, 7 days a week)
Or you may write to bank Bank INDIA, National Association, PO Box 2013, Buffalo, NY 14240
Your Right to Receive Documentation of Transfers
You will receive a periodic statement in the mail for each Account, unless you have chosen to receive eStatement Service, or you have an bank online-only Account that provides electronic delivery of all notices, statements and disclosures. Your statement will reflect all your transactions, including your Personal Internet Banking transactions. If you have registered for the Bill Pay service, your periodic statement will reflect bill payments.
Liability for Failure to Complete Personal Internet Banking Transactions<br/>
If we do not complete a Personal Internet Banking Transaction on time or in the correct amount according to this agreement with you, we will be liable for your losses or damages caused by such failure but not for any special or consequential damages, unless required by applicable law. However, there are some exceptions. We will not be liable for any indirect, incidental, special or consequential damages if our failure was not intentional and resulted from a bona fide error, notwithstanding our procedures to avoid such error, for instance:
IF you do not have enough available funds in your Account to make your transfer, unless you have authorized bank to use your usable balance from your bank Premier with Sweep Account, your Asset Management Account, your Commercial Asset Management Account, your Money Market Mutual Fund Account, or available credit from your MasterCard®, VISA®, Select Credit Account or Express Line Account.
IF your computer malfunctions.
IF the Web Browser or the processing center of bank or its agent that is used for Personal Internet Banking is not working properly and you knew or were advised by bank or its agent about this when you made the Internet Banking Transaction.
IF circumstances beyond our control (such as fire, flood, computer failure or interference from an outside force) prevent the Personal Internet Banking transaction from being properly made or completed.
IF your log on credentials have been reported lost or stolen or we have reason to believe that the Personal Internet Banking transaction is unauthorized.
IF the transaction would violate any applicable provision of any risk control program or applicable policies, procedures or practices, or government regulations.
IF we have reasonable cause not to honor an instruction for our protection or for yours.
IF your Personal Internet Banking access has been suspended.
IF the funds in your Account are subject to legal process or other encumbrance restricting the transfer.
IF the Bill Payment Process Date is not at least 5 (five) Business Days prior to the due date of such payment.
IF the payee has a mailing address outside the U.S. or if the Bill Payment is to pay any taxes, or to make a court-ordered or directed payment.
There may be other exceptions stated in our agreements with you.
In Case of Errors or Questions About Your Personal Internet Banking Transactions
If you think your Account statement sent to you by bank or transaction information obtained by you through Personal Internet Banking is wrong or if you need more information about a Personal Internet Banking transfer listed on that statement, contact us as soon as possible. You must notify us no later than 60 calendar days after we sent, or you obtained through Personal Internet Banking, the first statement in which the problem or error appeared. Call the telephone number on your statement or 1-800-975-bank (1-800-975-4722). Representatives are available Monday - Sunday 7:00am - 12:00am ET.
You may also write bank at:
bank Bank INDIA, National Association
PO Box 2013
Buffalo, NY 14240<br/>
Tell us your name and the Account number.
Describe the error or transfer you are unsure about, and explain as clearly as you can why you believe it is an error or why you need more information.
Tell us the dollar amount of the suspected error.
Tell us the date the error occurred.<br/>
If you inform us verbally, we may require that you send us your complaint or question in writing within 10 Business Days.
We will report back to you within 10 Business Days after we hear from you and will correct any error promptly. If we require more time, however, we may take up to 45 calendar days to investigate your complaint or question. If we decide to do this, we will credit your Account within 10 Business Days for the amount you think is in error, so that you can use the money during the time it takes us to complete our investigation. If we ask you to put your complaint or question in writing and we do not receive it within 10 Business Days, we do not have to re-credit your Account.
If a notice of error involves a Personal Internet Banking transaction that occurred within 30 days after the first deposit to the account was made, the time period for action listed above will be 20 Business Days in place of 10 Business Days and the time period for investigation will be 90 calendar days in place of 45 calendar days.
If we decide that there was no error, we will send you a written explanation within 3 Business Days after we finish our investigation. You may ask for copies of the documents that we used in our investigation.
If your Account is in the joint names of you and one or more other persons, then each of you will be responsible for Personal Internet Banking transactions made by any of you.
Electronic Delivery of Notices and Disclosures
If you choose the eStatement Service for bank Bank Product account(s), or, for your bank online-only Account(s) which all require the eStatement Service, you will receive an email alert when your periodic online statement is ready or when notices or other disclosures are available. It is your responsibility to inform us of any changes to your email address.
bank Bank Product accounts - Personal Checking accounts must be enrolled in RecordCheck® (your checks are not returned to you) to be eligible to receive an eStatement. Personal Savings accounts are eligible for eStatements. Credit Card and Select Credit accounts must be in good standing to be eligible for eStatements.
Any statement shown on Personal Internet Banking that does not have the electronic statement indicator selected will continue to be delivered through the U.S. Mail.
No paper statements, notices or other disclosures will be mailed for bank online-only Accounts.
Primary account holders enrolled for eStatements will receive their 1099-INT annual interest statement in the left navigation under eStatements after January 1st of each year. In the event that you are unable to print your 1099-INT from the Personal Internet Banking service you may request a paper copy by sending a BankMail request.
Accessing eStatements
bank will send an electronic notice to the email address provided and deliver selected periodic account statements, notices and other disclosures to your bank Personal Internet Banking account. You will have access to an electronic version of your deposit account statement(s) for up to 7 years and credit account statement(s) for up to 2 years. This service provides you with the flexibility to print and save account statements that are made available online. You may select electronic delivery of one or all of the listed statements. Electronic delivery is required for all bank online-only accounts.
Your paper statement on request
At your request, bank will send you a paper copy of your electronic statement previously delivered through the Personal Internet Banking service at any time. bank's standard fee then in effect and charged for paper delivery copies of account statements will apply. Paper copies of electronic statements can be requested by contacting bank's Customer Relationship Center at 1-800-975-4722 or other location as bank may advise. A request for a paper copy does not cause a termination of the electronic statement service. A paper copy of electronic statements can be obtained until the copy is no longer required to be maintained as a record for the designated account under applicable law or regulation.
bank will not mail to you paper copies of account disclosures, statements, notices and other communications for accounts included in your eStatement Service, including any applicable IRS Forms 1099. To request a paper copy of account disclosures, statements, notices, and other communications for bank Bank Product accounts, you must write to bank Bank INDIA, N.A., PO Box 4045, Buffalo, NY 14240 or NewRequest@us.hsbc.com.
If you want to withdraw consent for the eStatement Service for your bank online-only account(s), you will have to close the bank online-only account(s).
Joint personal account holders
Each joint account holder may sign up to receive eStatements individually. For Credit Card and Select Credit accounts, only primary cardmembers/accountholders may register for eStatements. To cancel the eStatement Service, only one owner of the account needs to request the change. The eStatement Service cannot be cancelled for bank online-only Accounts.
bank may deliver paper disclosures at its discretion, bank may deliver statements, notices, agreements, disclosures and information about your account(s) in paper form to your last postal mailing address of record.
bank will send an email alert when your eStatement is available The only notice that you will receive advising you that your electronic periodic statement has been posted to Personal Internet Banking will be by email alert sent to the single, specific email address selected and confirmed and validated by you upon enrollment. One attempt will be made to notify you by email that your eStatement is available to view. If the email address provided is returned as "undeliverable", you will be prompted to enter a new email address the next time you attempt to use the eStatement Service in Personal Internet Banking. This email will be the only notice you will receive and no other notice will be sent. Any and all notices sent by bank to the email address will constitute sufficient and effective delivery to you and all owners of the information contained in your electronic statement whether or not you access or review the notice, Personal Internet Banking site or specific electronic statement, and shall be deemed to have been delivered to you personally, whether actually received or not. You agree to maintain access to Personal Internet Banking in a manner that gives you continuous ability to access, review and print your electronic statements and to receive and access all notices sent to you at the designated email address. It is your sole responsibility to advise bank immediately of any changes or updates to the designated email address. There are certain risks associated with the transmission of email notices through the Internet including but not limited to unauthorized access, system outages, delays, disruption in telecommunications services and the Internet. Email is not private or secure. The email notice sent to you by email is an unencrypted, automatic notice. Although the notice is not intended to contain personally identifiable confidential financial information, it may contain in its design, part or all of your name or other identifier, which could be seen or intercepted by others if delivered to your business address or other computers or electronic devices not exclusively under your control. Do NOT respond to the email notices by return email, or use the reply function to request information, service, paper copies or other items or to revoke consent. bank will not be responsible to act upon requests made in that manner.
Canceling the eStatement Service
You or any designated account owner may revoke consent for the eStatement Service for one or more bank Bank account(s) accessed through Personal Internet Banking, other than bank online-only account(s), at any time by un-enrolling your account(s) through the eStatement Service, Modify Settings page located in bank's Personal Internet Banking. Electronic posting of your electronic statement on Personal Internet Banking and transmission of related email notices will continue until: (1) termination of the eStatement Service, (2) termination of your designated account(s) with bank, or (3) termination of your Personal Internet Banking service with bank. bank may terminate the eStatement Service for any or all designated accounts at any time. Upon such termination, delivery of paper copies of periodic account statements, notices and disclosures will resume within a reasonable time. Termination of the eStatement Service does not affect the validity or legal effect of any eStatement Service delivered to you or any owners of the account(s) through Personal Internet Banking. Termination of the eStatement Service does not terminate the Personal Internet Banking service unless otherwise so stated.
To withdraw consent, or to provide updated information on how bank Bank INDIA, N.A. may contact you electronically, you must write to bank Bank INDIA, N.A., PO Box 4045, Buffalo, NY 14240 or NewRequest@us.hsbc.com.
Hardware and Software Requirements
You agree that you have or will have access at all times to a personal computer capable of supporting at your cost; high level browser encryption, Internet access, a valid email address, and Personal Internet Banking. You must also have access to Adobe Acrobat Reader to utilize PDF files.
If the method of electronic delivery by bank changes so as to require additional software, upgrades, plug-ins or additional security features in your hardware of software system used by you for bank Bank Products account(s), you may terminate the eStatement Service or you may agree to upgrade your hardware or software system to the required standards. If you want to withdraw consent for electronic delivery for your bank online-only Account(s), you will have to close the bank online-only Account(s).
If bank determines that a change to the eStatement Service concerning any future system or hardware enhancement creates a material risk that you may not be able to access or retain a subsequent electronic record, bank will notify you of such change and allow you to withdraw consent for this eStatement Service for bank Bank Products account(s), whereupon bank may terminate this service until you choose to enroll again in this service and deliver a new consent to participate in this service by accepting bank's online consent form posted on Personal Internet Banking. If you want to withdraw consent for electronic delivery for your bank online-only Account(s), you will have to close the bank online-only Account(s).
You understand that your accessing electronic statements through Personal Internet Banking and receiving email notices may incur certain costs associated with email, electronic access, downloading, online time and subscription costs associated with Internet and telecommunications service providers, paper and printing costs, and equipment or software upgrades if necessary. You agree that you will pay all such costs and expenses in connection with your use of the eStatement Service.
Indemnification
Except to the extent that we are liable under these Terms and Conditions or an agreement that governs an Account of yours, if you are an owner of an Account, you agree to indemnify and hold us, our directors, officers, employees and agents harmless from all loss, liability, claims, demands, judgments and expenses arising out of or in any way connected with an Account or the performance of Personal Internet Banking, including any service provider therein. This indemnification is provided without regard to whether our claim for indemnification is due to the use of Personal Internet Banking by you or your authorized representative.
Limitation of Liability
Except as specifically provided in these Terms and Conditions or where applicable law requires a different result, NEITHER WE NOR OUR SERVICE PROVIDERS OR OTHER AGENTS WILL BE LIABLE FOR ANY LOSS OR LIABILITY RESULTING IN WHOLE OR IN PART FROM ANY ACT OR FAILURE TO ACT OF YOUR EQUIPMENT OR SOFTWARE, OR THAT OF AN INTERNET BROWSER PROVIDER, OR BY AN INTERNET ACCESS PROVIDER, BY AN ONLINE SERVICE PROVIDER OR BY AN AGENT OR SUBCONTRACTOR FOR ANY OF THEM, NOR WILL WE OR OUR SERVICE PROVIDERS OR OTHER AGENTS BE RESPONSIBLE FOR ANY DIRECT, INDIRECT, SPECIAL, OR CONSEQUENTIAL ECONOMIC OR OTHER DAMAGES ARISING IN ANY WAY OUT OF YOUR ACCESS TO OR USE OF, OR FAILURE TO OBTAIN ACCESS TO PERSONAL INTERNET BANKING, INCLUDING ANY SERVICE PROVIDER THEREIN.
BankMail (Secured Email)
We will respond to your BankMail promptly after we receive it. Do not use BankMail if you need to contact us immediately. Call us at 1-800-975-bank (1-800-975-4722) Monday - Sunday 7:00am - 12:00am ET. We may use BankMail to communicate occasional updates of new features, surveys and special offers from bank.
Recording of Phone Calls and Email
You authorize bank and its agents to record or copy any phone call made to or email sent to bank concerning Internet Banking.
Fees
Personal Internet Banking and the Bill Pay service are FREE to all bank Customers. Your Internet service provider may charge fees. Electronic transaction charges may apply. Please refer to your account agreement.
Business Accounts on Personal Internet Banking
You acknowledge that bank offers banknet for business accounts. banknet provides additional security features. Personal Internet Banking is primarily intended for consumer accounts. banknet provides built-in security features permitting you to establish transfer and account access limitations that are not available on Personal Internet Banking.
You shall at all times indemnify, defend and hold bank harmless from and against all actions, proceedings, claims or loss, damage, costs and expenses which may be brought against bank or incurred by bank and which shall have arisen in connection with the instructions transmitted by Personal Internet Banking relating to your business accounts.
Changes to the Terms of the Agreement
bank may change this Agreement by electronically sending to you a BankMail notice, mailing to you a notice or posting a notice of such change in an bank branch where you maintain your Account. However, if the change results in (1) increased or new fees or charges, (2) increased liability for you, (3) fewer types of available Personal Internet Banking services, or (4) stricter limitations on the frequency or dollar amounts of transfers, then, unless the change must be made immediately for security reasons, at least 30 days before the effective date of the change bank will either electronically send you a BankMail notice or mail a written notice to you.
Any notice to you will take effect when it is personally delivered to you or by BankMail to you by Internet Banking or mailed to the last address we have for you in our records.
Other Rules<br/>
Personal Internet Banking transactions are also subject to bank account agreements and rules, and your access and use of Personal Internet Banking is also subject to these terms and conditions.
Termination<br/>
bank may cancel your Personal Internet Banking access without prior notice if there has been no Personal Internet Banking activity for a period of 6 consecutive months or for any other reason. bank may suspend your Bill Payment service without prior notice if there has been no Bill Payment activity for a period of 3 consecutive months or for any other reason.
Assignment<br/>
We may assign our rights under this Agreement to a company affiliated with us or to any other party.
Applicable Law<br/>
This Agreement shall be governed by the laws of the State of New York and applicable federal law and regulations.
(Rev 05/21/14)<br/>
            </div>
        </div>
<?php include 'footer.php'; ?>